config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  resources :players, only: [:new, :show, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :characters, only: [:new, :create]
  resources :factions, only: [:show] do
    resources :planets, only:[:new, :index, :create, :show]
  end
  post 'players/search/:name', to: 'players#search'
  post 'players/search/', to: 'players#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
# frozen_string_literal: true

class Character < ApplicationRecord
  validates :name, :faction, presence: true
  belongs_to :player, required: nil
  belongs_to :faction, required: nil
end

app/models/faction.rb
# frozen_string_literal: true

class Faction < ApplicationRecord
  validates :name, :description, presence: true
  has_many :characters
  has_many :planets
  has_many :players, through: :characters
end

app/models/planet.rb
# frozen_string_literal: true

class Planet < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  belongs_to :faction, required: nil
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :password, presence: true
  has_many :characters
  has_many :factions, through: :characters
  has_secure_password

  scope :search, ->(name) { where(name: name) }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def logged_in?
    session[:player_id]
  end

  def current_player
    Player.find(session[:player_id])
  end

  def authorize
    redirect_to new_session_path unless logged_in?
  end
end

app/controllers/characters_controller.rb
# frozen_string_literal: true

class CharactersController < ApplicationController
  before_action :authorize, only: %i[new create]
  def new
    @character = Character.new
    @player = current_player
  end

  # create character
  def create
    name = params[:character][:name]
    faction_id = params[:character][:faction_id]
    character = Character.new(name: name, faction_id: faction_id)
    character.player_id = session[:player_id]
    character.save!
    # check value of save -> return error

    respond_to do |format|
      format.json do
        render json: character.to_json(include: { faction: { only: :name } })
      end
    end
  end

private

  def character_params
    params.require(:character).permit(:faction_id, :name)
  end
end

app/controllers/factions_controller.rb
# frozen_string_literal: true

class FactionsController < ApplicationController
  before_action :authorize, only: %i[index show]
  def new
    @faction = Faction.new
  end

  def index
    @factions = Faction.all
  end

  def show
    @faction = Faction.find(params[:id])
    @player = current_player
  end
end

app/controllers/planets_controller.rb
# frozen_string_literal: true

class PlanetsController < ApplicationController
  before_action :authorize, only: %i[new index create show]
  def new
    @planet = Planet.new
    @faction = Faction.find(params[:faction_id])
  end

  def index
    @planets = Planet.all
    @planet_name = @planets.find(params[:faction_id]).name
    faction_planets = Planet.where(faction_id: params[:faction_id])
    render json: faction_planets.to_json
    # json format
  end

  def create
    planet = Planet.create(planet_params)
    faction = Faction.find(params[:faction_id])
    planet.faction = faction
    if planet.save
      redirect_to faction_planet_path(faction, planet)
    else
      flash[:error] = "Invalid Planet Name"
      redirect_to new_faction_planet_path
    end
  end

  def show
    @planet = Planet.find(params[:id])
    @faction = Faction.find(params[:faction_id])
  end

private

  def planet_params
    params.require(:planet).permit(
      :name,
      :faction_id
    )
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  before_action :authorize, only: %i[index show search]

  def new
    @player = Player.new
  end

  def index
    @players = Player.all
    @player = Player.new
    @current_player = current_player
  end

  # Player Dashboard
  def show
    @player = Player.find(params[:id])
  end

  # Player Search
  def search
    player = Player.find_by(name: params[:name])
    render(json: player.to_json(include: {
                                  characters: {
                                    include: {
                                      faction: { only: :name },
                                    },
                                    only: :name,
                                  },
                                },
                                except: :password_digest))
  end

  # Signup
  def create
    if params[:password] == params[:password_confirmation]
      @player = Player.new(player_params)
      signup
    else
      redirect_to new_player_path
    end
  end

private

  def player_params
    params.require(:player).permit(:name, :password, :password_confirmation)
  end

  def signup
    if @player.save
      session[:player_id] = @player.id
      redirect_to player_path(@player)
    else
      flash[:error] = @player.errors.full_messages
      redirect_to new_player_path
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :authorize, only: [:destroy]
  def new
    @player = Player.new
  end

  # login
  def create
    player = Player.find_by(name: params[:player][:name])
    if player&.authenticate(params[:player][:password])
      session[:player_id] = player.id
      redirect_to player_path(player)
    else
      flash[:error] = "Invalid Login"
      redirect_to "/sessions/new"
    end
  end

  # logout
  def destroy
    session.delete :player_id
    redirect_to "/"
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/characters/new.html.erb
<h1>
  Create a Hero
</h1>

<%= form_for @character do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>
  <p>
    Select Faction:
  </p>
  <%= f.collection_select(:faction_id, Faction.all, :id, :name, include_blank: true) %>
  <%= f.submit "Create Hero" %>
<% end %>
</br>
<%= link_to "<- Back to #{@player.name}'s Dashboard", player_path(@player) %>
</br>

app/views/factions/show.html.erb
<h1>
  Faction Information
</h1>

<h2>
  <u>
    <%= @faction.name %>
  </u>
</h2>
<h3>
  <%= @faction.description %>
</h3>

<%= form_for @faction do |f| %>
  <%= f.hidden_field :id %>
  <%= f.submit "#{@faction.name} Planets" %>
<% end %>
</br>

<div class="result"></div>

</p>
<p>
  <%= link_to "Logout", session_path, method: :delete %>
</p>
<%= link_to "Create New Planet for #{@faction.name} Colonization", new_faction_planet_path(@faction) %>
<p>
  <%= link_to "<-Back to #{@player.name}'s Dashboard", player_path(@player) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Starcraft</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <% if value.respond_to?(:each) %>
          <% value.each do |line| %>
            <%= line %>
            <br />
          <% end %>
        <% else %>
          <%= value %>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/planets/new.html.erb
<h1>
  Create a Planet
</h1>
<%= form_for @planet, url: faction_planets_path(@faction, @planet) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %></br>
  <%= f.submit "Create Planet" %>
<% end %>
<p>
  <%= link_to "<-Back to Faction Information", faction_path(@faction) %>
</p>

app/views/planets/show.html.erb
<h1>
  <%= @planet.name %> is under <%= @planet.faction.name %> control
</h1>
<%= link_to "<- Back to Faction Information", faction_path(@faction) %>

app/views/players/index.html.erb
<h1>
  Search Player Name:
</h1>
<%= form_for @player do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Search" %>
<% end %>

<div class="result"></div>
<p>
  <%= link_to "<- Back to #{@current_player.name}'s Dashboard", player_path(@current_player) %>
</p>

<script>
  $(document).on('turbolinks:load', function() {
    $('.new_player').submit(function(event) {
      event.preventDefault()
      const name = $("#player_name").val()

      $.post(`/players/search/${name}`, function(data) {
      if (data) {
        const player = new Player(data.name, data.characters)
        $(".result").html(player.playerEl())
      } else {
        $(".result").html("No player found.")
      }
    })
  })
})
</script>

app/views/players/new.html.erb
<h1>
  Signup
</h1>
<%= form_for @player do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>
  <%= f.label :password %>:
  <%= f.password_field :password %>
  </br>
  <%= f.submit "Create Player" %>
<% end %>
</br>
<%= link_to "Login", new_session_path %>
</br>
<%= link_to "<- Back Home", root_path %>

app/views/players/show.html.erb
<pre>
    ____             __    __                         __
   / __ \____ ______/ /_  / /_  ____  ____ __________/ /
  / / / / __ `/ ___/ __ \/ __ \/ __ \/ __ `/ ___/ __  /
 / /_/ / /_/ (__  ) / / / /_/ / /_/ / /_/ / /  / /_/ /
/_____/\__,_/____/_/ /_/_.___/\____/\__,_/_/   \__,_/
</pre>
<%= link_to "Logout", session_path, method: :delete %>
<h1>
  <%= @player.name %>
</h1>
<p>
  <%= link_to "Search For Player", players_path %>
</p>

<h3>
  <u>
    <%= @player.name %>'s Hero List:
  </u>
</h3>
<% @player.characters.each do |char| %>

    <p>
      <b>Name</b>: <%= char.name %>
      </br>
      <b>Faction</b>: <%= link_to char.faction.name, faction_path(char.faction) %>
    </p>
<% end %>
  <div id="character_list">
  </div>
<h3>
  <u>
    Create New Hero
  </u>
</h3>
<%= form_for @player.characters.new do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>
  <p>
    Select Faction:
  </p>
  <%= f.collection_select(:faction_id, Faction.all, :id, :name, include_blank: true) %>
  <%= f.submit "Create Hero" %>
<% end %>
<script>
  addCharacterFormListener()
</script>

app/views/static_pages/home.html.erb
<pre>

  _________ __                                     _____  __
 /   _____//  |______ _______   ________________ _/ ____\/  |_
 \_____  \\   __\__  \\_  __ \_/ ___\_  __ \__  \\   __\\   __\
 /        \|  |  / __ \|  | \/\  \___|  | \// __ \|  |   |  |
/_______  /|__| (____  /__|    \___  >__|  (____  /__|   |__|
        \/           \/            \/           \/
</pre>
<%= link_to "Signup", new_player_path %>
</br>
</br>
<%= link_to "Login", new_session_path %>